// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/mod_service/mod_service.proto

package mod_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModActionType int32

const (
	ModActionType_MUTE                    ModActionType = 0
	ModActionType_SUSPEND_ACCOUNT         ModActionType = 1
	ModActionType_SUSPEND_RATED_GAMES     ModActionType = 2
	ModActionType_SUSPEND_GAMES           ModActionType = 3
	ModActionType_RESET_RATINGS           ModActionType = 4
	ModActionType_RESET_STATS             ModActionType = 5
	ModActionType_RESET_STATS_AND_RATINGS ModActionType = 6
	ModActionType_REMOVE_CHAT             ModActionType = 7
	ModActionType_DELETE_ACCOUNT          ModActionType = 8
)

// Enum value maps for ModActionType.
var (
	ModActionType_name = map[int32]string{
		0: "MUTE",
		1: "SUSPEND_ACCOUNT",
		2: "SUSPEND_RATED_GAMES",
		3: "SUSPEND_GAMES",
		4: "RESET_RATINGS",
		5: "RESET_STATS",
		6: "RESET_STATS_AND_RATINGS",
		7: "REMOVE_CHAT",
		8: "DELETE_ACCOUNT",
	}
	ModActionType_value = map[string]int32{
		"MUTE":                    0,
		"SUSPEND_ACCOUNT":         1,
		"SUSPEND_RATED_GAMES":     2,
		"SUSPEND_GAMES":           3,
		"RESET_RATINGS":           4,
		"RESET_STATS":             5,
		"RESET_STATS_AND_RATINGS": 6,
		"REMOVE_CHAT":             7,
		"DELETE_ACCOUNT":          8,
	}
)

func (x ModActionType) Enum() *ModActionType {
	p := new(ModActionType)
	*p = x
	return p
}

func (x ModActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mod_service_mod_service_proto_enumTypes[0].Descriptor()
}

func (ModActionType) Type() protoreflect.EnumType {
	return &file_proto_mod_service_mod_service_proto_enumTypes[0]
}

func (x ModActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModActionType.Descriptor instead.
func (ModActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{0}
}

type EmailType int32

const (
	EmailType_DEFAULT  EmailType = 0
	EmailType_CHEATING EmailType = 1
	EmailType_DELETION EmailType = 2
)

// Enum value maps for EmailType.
var (
	EmailType_name = map[int32]string{
		0: "DEFAULT",
		1: "CHEATING",
		2: "DELETION",
	}
	EmailType_value = map[string]int32{
		"DEFAULT":  0,
		"CHEATING": 1,
		"DELETION": 2,
	}
)

func (x EmailType) Enum() *EmailType {
	p := new(EmailType)
	*p = x
	return p
}

func (x EmailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mod_service_mod_service_proto_enumTypes[1].Descriptor()
}

func (EmailType) Type() protoreflect.EnumType {
	return &file_proto_mod_service_mod_service_proto_enumTypes[1]
}

func (x EmailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailType.Descriptor instead.
func (EmailType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{1}
}

type NotoriousGameType int32

const (
	NotoriousGameType_GOOD                 NotoriousGameType = 0
	NotoriousGameType_NO_PLAY              NotoriousGameType = 1
	NotoriousGameType_SITTING              NotoriousGameType = 2
	NotoriousGameType_SANDBAG              NotoriousGameType = 3
	NotoriousGameType_NO_PLAY_DENIED_NUDGE NotoriousGameType = 4
	NotoriousGameType_EXCESSIVE_PHONIES    NotoriousGameType = 5
)

// Enum value maps for NotoriousGameType.
var (
	NotoriousGameType_name = map[int32]string{
		0: "GOOD",
		1: "NO_PLAY",
		2: "SITTING",
		3: "SANDBAG",
		4: "NO_PLAY_DENIED_NUDGE",
		5: "EXCESSIVE_PHONIES",
	}
	NotoriousGameType_value = map[string]int32{
		"GOOD":                 0,
		"NO_PLAY":              1,
		"SITTING":              2,
		"SANDBAG":              3,
		"NO_PLAY_DENIED_NUDGE": 4,
		"EXCESSIVE_PHONIES":    5,
	}
)

func (x NotoriousGameType) Enum() *NotoriousGameType {
	p := new(NotoriousGameType)
	*p = x
	return p
}

func (x NotoriousGameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotoriousGameType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mod_service_mod_service_proto_enumTypes[2].Descriptor()
}

func (NotoriousGameType) Type() protoreflect.EnumType {
	return &file_proto_mod_service_mod_service_proto_enumTypes[2]
}

func (x NotoriousGameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotoriousGameType.Descriptor instead.
func (NotoriousGameType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{2}
}

type ModAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          ModActionType          `protobuf:"varint,2,opt,name=type,proto3,enum=mod_service.ModActionType" json:"type,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	RemovedTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=removed_time,json=removedTime,proto3" json:"removed_time,omitempty"`
	Channel       string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	MessageId     string                 `protobuf:"bytes,8,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ApplierUserId string                 `protobuf:"bytes,9,opt,name=applier_user_id,json=applierUserId,proto3" json:"applier_user_id,omitempty"`
	RemoverUserId string                 `protobuf:"bytes,10,opt,name=remover_user_id,json=removerUserId,proto3" json:"remover_user_id,omitempty"`
	ChatText      string                 `protobuf:"bytes,11,opt,name=chat_text,json=chatText,proto3" json:"chat_text,omitempty"`
	// Note: an optional note from the moderator.
	Note          string    `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	EmailType     EmailType `protobuf:"varint,13,opt,name=email_type,json=emailType,proto3,enum=mod_service.EmailType" json:"email_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModAction) Reset() {
	*x = ModAction{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModAction) ProtoMessage() {}

func (x *ModAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModAction.ProtoReflect.Descriptor instead.
func (*ModAction) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{0}
}

func (x *ModAction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ModAction) GetType() ModActionType {
	if x != nil {
		return x.Type
	}
	return ModActionType_MUTE
}

func (x *ModAction) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ModAction) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ModAction) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ModAction) GetRemovedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RemovedTime
	}
	return nil
}

func (x *ModAction) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ModAction) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ModAction) GetApplierUserId() string {
	if x != nil {
		return x.ApplierUserId
	}
	return ""
}

func (x *ModAction) GetRemoverUserId() string {
	if x != nil {
		return x.RemoverUserId
	}
	return ""
}

func (x *ModAction) GetChatText() string {
	if x != nil {
		return x.ChatText
	}
	return ""
}

func (x *ModAction) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ModAction) GetEmailType() EmailType {
	if x != nil {
		return x.EmailType
	}
	return EmailType_DEFAULT
}

type ModActionsMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       map[string]*ModAction  `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModActionsMap) Reset() {
	*x = ModActionsMap{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModActionsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModActionsMap) ProtoMessage() {}

func (x *ModActionsMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModActionsMap.ProtoReflect.Descriptor instead.
func (*ModActionsMap) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{1}
}

func (x *ModActionsMap) GetActions() map[string]*ModAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ModActionsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*ModAction           `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModActionsList) Reset() {
	*x = ModActionsList{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModActionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModActionsList) ProtoMessage() {}

func (x *ModActionsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModActionsList.ProtoReflect.Descriptor instead.
func (*ModActionsList) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{2}
}

func (x *ModActionsList) GetActions() []*ModAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type GetActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionsRequest) Reset() {
	*x = GetActionsRequest{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsRequest) ProtoMessage() {}

func (x *GetActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionsRequest.ProtoReflect.Descriptor instead.
func (*GetActionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetActionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ModActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModActionResponse) Reset() {
	*x = ModActionResponse{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModActionResponse) ProtoMessage() {}

func (x *ModActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModActionResponse.ProtoReflect.Descriptor instead.
func (*ModActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{4}
}

type NotoriousGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          NotoriousGameType      `protobuf:"varint,2,opt,name=type,proto3,enum=mod_service.NotoriousGameType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotoriousGame) Reset() {
	*x = NotoriousGame{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotoriousGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotoriousGame) ProtoMessage() {}

func (x *NotoriousGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotoriousGame.ProtoReflect.Descriptor instead.
func (*NotoriousGame) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{5}
}

func (x *NotoriousGame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotoriousGame) GetType() NotoriousGameType {
	if x != nil {
		return x.Type
	}
	return NotoriousGameType_GOOD
}

func (x *NotoriousGame) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ResetNotorietyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetNotorietyRequest) Reset() {
	*x = ResetNotorietyRequest{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetNotorietyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetNotorietyRequest) ProtoMessage() {}

func (x *ResetNotorietyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetNotorietyRequest.ProtoReflect.Descriptor instead.
func (*ResetNotorietyRequest) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResetNotorietyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResetNotorietyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetNotorietyResponse) Reset() {
	*x = ResetNotorietyResponse{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetNotorietyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetNotorietyResponse) ProtoMessage() {}

func (x *ResetNotorietyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetNotorietyResponse.ProtoReflect.Descriptor instead.
func (*ResetNotorietyResponse) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{7}
}

type GetNotorietyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotorietyReportRequest) Reset() {
	*x = GetNotorietyReportRequest{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotorietyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotorietyReportRequest) ProtoMessage() {}

func (x *GetNotorietyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotorietyReportRequest.ProtoReflect.Descriptor instead.
func (*GetNotorietyReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetNotorietyReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NotorietyReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Games         []*NotoriousGame       `protobuf:"bytes,2,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotorietyReport) Reset() {
	*x = NotorietyReport{}
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotorietyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotorietyReport) ProtoMessage() {}

func (x *NotorietyReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mod_service_mod_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotorietyReport.ProtoReflect.Descriptor instead.
func (*NotorietyReport) Descriptor() ([]byte, []int) {
	return file_proto_mod_service_mod_service_proto_rawDescGZIP(), []int{9}
}

func (x *NotorietyReport) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *NotorietyReport) GetGames() []*NotoriousGame {
	if x != nil {
		return x.Games
	}
	return nil
}

var File_proto_mod_service_mod_service_proto protoreflect.FileDescriptor

const file_proto_mod_service_mod_service_proto_rawDesc = "" +
	"\n" +
	"#proto/mod_service/mod_service.proto\x12\vmod_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x04\n" +
	"\tModAction\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.mod_service.ModActionTypeR\x04type\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12=\n" +
	"\fremoved_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vremovedTime\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"message_id\x18\b \x01(\tR\tmessageId\x12&\n" +
	"\x0fapplier_user_id\x18\t \x01(\tR\rapplierUserId\x12&\n" +
	"\x0fremover_user_id\x18\n" +
	" \x01(\tR\rremoverUserId\x12\x1b\n" +
	"\tchat_text\x18\v \x01(\tR\bchatText\x12\x12\n" +
	"\x04note\x18\f \x01(\tR\x04note\x125\n" +
	"\n" +
	"email_type\x18\r \x01(\x0e2\x16.mod_service.EmailTypeR\temailType\"\xa6\x01\n" +
	"\rModActionsMap\x12A\n" +
	"\aactions\x18\x01 \x03(\v2'.mod_service.ModActionsMap.ActionsEntryR\aactions\x1aR\n" +
	"\fActionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.mod_service.ModActionR\x05value:\x028\x01\"B\n" +
	"\x0eModActionsList\x120\n" +
	"\aactions\x18\x01 \x03(\v2\x16.mod_service.ModActionR\aactions\",\n" +
	"\x11GetActionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x13\n" +
	"\x11ModActionResponse\"\x8e\x01\n" +
	"\rNotoriousGame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.mod_service.NotoriousGameTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"0\n" +
	"\x15ResetNotorietyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x18\n" +
	"\x16ResetNotorietyResponse\"4\n" +
	"\x19GetNotorietyReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\x0fNotorietyReport\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x120\n" +
	"\x05games\x18\x02 \x03(\v2\x1a.mod_service.NotoriousGameR\x05games*\xc0\x01\n" +
	"\rModActionType\x12\b\n" +
	"\x04MUTE\x10\x00\x12\x13\n" +
	"\x0fSUSPEND_ACCOUNT\x10\x01\x12\x17\n" +
	"\x13SUSPEND_RATED_GAMES\x10\x02\x12\x11\n" +
	"\rSUSPEND_GAMES\x10\x03\x12\x11\n" +
	"\rRESET_RATINGS\x10\x04\x12\x0f\n" +
	"\vRESET_STATS\x10\x05\x12\x1b\n" +
	"\x17RESET_STATS_AND_RATINGS\x10\x06\x12\x0f\n" +
	"\vREMOVE_CHAT\x10\a\x12\x12\n" +
	"\x0eDELETE_ACCOUNT\x10\b*4\n" +
	"\tEmailType\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\f\n" +
	"\bCHEATING\x10\x01\x12\f\n" +
	"\bDELETION\x10\x02*u\n" +
	"\x11NotoriousGameType\x12\b\n" +
	"\x04GOOD\x10\x00\x12\v\n" +
	"\aNO_PLAY\x10\x01\x12\v\n" +
	"\aSITTING\x10\x02\x12\v\n" +
	"\aSANDBAG\x10\x03\x12\x18\n" +
	"\x14NO_PLAY_DENIED_NUDGE\x10\x04\x12\x15\n" +
	"\x11EXCESSIVE_PHONIES\x10\x052\xf9\x03\n" +
	"\n" +
	"ModService\x12K\n" +
	"\fApplyActions\x12\x1b.mod_service.ModActionsList\x1a\x1e.mod_service.ModActionResponse\x12L\n" +
	"\rRemoveActions\x12\x1b.mod_service.ModActionsList\x1a\x1e.mod_service.ModActionResponse\x12H\n" +
	"\n" +
	"GetActions\x12\x1e.mod_service.GetActionsRequest\x1a\x1a.mod_service.ModActionsMap\x12O\n" +
	"\x10GetActionHistory\x12\x1e.mod_service.GetActionsRequest\x1a\x1b.mod_service.ModActionsList\x12Z\n" +
	"\x12GetNotorietyReport\x12&.mod_service.GetNotorietyReportRequest\x1a\x1c.mod_service.NotorietyReport\x12Y\n" +
	"\x0eResetNotoriety\x12\".mod_service.ResetNotorietyRequest\x1a#.mod_service.ResetNotorietyResponseB\xa3\x01\n" +
	"\x0fcom.mod_serviceB\x0fModServiceProtoP\x01Z7github.com/woogles-io/liwords/rpc/api/proto/mod_service\xa2\x02\x03MXX\xaa\x02\n" +
	"ModService\xca\x02\n" +
	"ModService\xe2\x02\x16ModService\\GPBMetadata\xea\x02\n" +
	"ModServiceb\x06proto3"

var (
	file_proto_mod_service_mod_service_proto_rawDescOnce sync.Once
	file_proto_mod_service_mod_service_proto_rawDescData []byte
)

func file_proto_mod_service_mod_service_proto_rawDescGZIP() []byte {
	file_proto_mod_service_mod_service_proto_rawDescOnce.Do(func() {
		file_proto_mod_service_mod_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mod_service_mod_service_proto_rawDesc), len(file_proto_mod_service_mod_service_proto_rawDesc)))
	})
	return file_proto_mod_service_mod_service_proto_rawDescData
}

var file_proto_mod_service_mod_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_mod_service_mod_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_mod_service_mod_service_proto_goTypes = []any{
	(ModActionType)(0),                // 0: mod_service.ModActionType
	(EmailType)(0),                    // 1: mod_service.EmailType
	(NotoriousGameType)(0),            // 2: mod_service.NotoriousGameType
	(*ModAction)(nil),                 // 3: mod_service.ModAction
	(*ModActionsMap)(nil),             // 4: mod_service.ModActionsMap
	(*ModActionsList)(nil),            // 5: mod_service.ModActionsList
	(*GetActionsRequest)(nil),         // 6: mod_service.GetActionsRequest
	(*ModActionResponse)(nil),         // 7: mod_service.ModActionResponse
	(*NotoriousGame)(nil),             // 8: mod_service.NotoriousGame
	(*ResetNotorietyRequest)(nil),     // 9: mod_service.ResetNotorietyRequest
	(*ResetNotorietyResponse)(nil),    // 10: mod_service.ResetNotorietyResponse
	(*GetNotorietyReportRequest)(nil), // 11: mod_service.GetNotorietyReportRequest
	(*NotorietyReport)(nil),           // 12: mod_service.NotorietyReport
	nil,                               // 13: mod_service.ModActionsMap.ActionsEntry
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_proto_mod_service_mod_service_proto_depIdxs = []int32{
	0,  // 0: mod_service.ModAction.type:type_name -> mod_service.ModActionType
	14, // 1: mod_service.ModAction.start_time:type_name -> google.protobuf.Timestamp
	14, // 2: mod_service.ModAction.end_time:type_name -> google.protobuf.Timestamp
	14, // 3: mod_service.ModAction.removed_time:type_name -> google.protobuf.Timestamp
	1,  // 4: mod_service.ModAction.email_type:type_name -> mod_service.EmailType
	13, // 5: mod_service.ModActionsMap.actions:type_name -> mod_service.ModActionsMap.ActionsEntry
	3,  // 6: mod_service.ModActionsList.actions:type_name -> mod_service.ModAction
	2,  // 7: mod_service.NotoriousGame.type:type_name -> mod_service.NotoriousGameType
	14, // 8: mod_service.NotoriousGame.created_at:type_name -> google.protobuf.Timestamp
	8,  // 9: mod_service.NotorietyReport.games:type_name -> mod_service.NotoriousGame
	3,  // 10: mod_service.ModActionsMap.ActionsEntry.value:type_name -> mod_service.ModAction
	5,  // 11: mod_service.ModService.ApplyActions:input_type -> mod_service.ModActionsList
	5,  // 12: mod_service.ModService.RemoveActions:input_type -> mod_service.ModActionsList
	6,  // 13: mod_service.ModService.GetActions:input_type -> mod_service.GetActionsRequest
	6,  // 14: mod_service.ModService.GetActionHistory:input_type -> mod_service.GetActionsRequest
	11, // 15: mod_service.ModService.GetNotorietyReport:input_type -> mod_service.GetNotorietyReportRequest
	9,  // 16: mod_service.ModService.ResetNotoriety:input_type -> mod_service.ResetNotorietyRequest
	7,  // 17: mod_service.ModService.ApplyActions:output_type -> mod_service.ModActionResponse
	7,  // 18: mod_service.ModService.RemoveActions:output_type -> mod_service.ModActionResponse
	4,  // 19: mod_service.ModService.GetActions:output_type -> mod_service.ModActionsMap
	5,  // 20: mod_service.ModService.GetActionHistory:output_type -> mod_service.ModActionsList
	12, // 21: mod_service.ModService.GetNotorietyReport:output_type -> mod_service.NotorietyReport
	10, // 22: mod_service.ModService.ResetNotoriety:output_type -> mod_service.ResetNotorietyResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_mod_service_mod_service_proto_init() }
func file_proto_mod_service_mod_service_proto_init() {
	if File_proto_mod_service_mod_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mod_service_mod_service_proto_rawDesc), len(file_proto_mod_service_mod_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mod_service_mod_service_proto_goTypes,
		DependencyIndexes: file_proto_mod_service_mod_service_proto_depIdxs,
		EnumInfos:         file_proto_mod_service_mod_service_proto_enumTypes,
		MessageInfos:      file_proto_mod_service_mod_service_proto_msgTypes,
	}.Build()
	File_proto_mod_service_mod_service_proto = out.File
	file_proto_mod_service_mod_service_proto_goTypes = nil
	file_proto_mod_service_mod_service_proto_depIdxs = nil
}
