ALTER TABLE users
    ALTER COLUMN uuid DROP NOT NULL,
    ALTER COLUMN username DROP NOT NULL,
    ALTER COLUMN email DROP NOT NULL,
    ALTER COLUMN password DROP NOT NULL,
    ALTER COLUMN internal_bot DROP NOT NULL,
    ALTER COLUMN internal_bot DROP DEFAULT,
    ALTER COLUMN notoriety DROP NOT NULL,
    ALTER COLUMN notoriety DROP DEFAULT;

ALTER TABLE profiles
    ALTER COLUMN user_id DROP NOT NULL;
