
FROM node:14-alpine3.10

WORKDIR /opt/liwords-ui/

ENV PATH /opt/liwords-ui/node_modules/.bin:$PATH

COPY ./liwords-ui/package.json ./
COPY ./liwords-ui/package-lock.json ./

RUN npm ci

EXPOSE 3000

CMD ["npm", "start"]