FROM golang

RUN apt-get update
RUN apt-get install -y unzip

# add protoc
ENV PROTOBUF_URL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip
RUN curl -L -o /tmp/protobuf.zip $PROTOBUF_URL
WORKDIR /tmp/
RUN unzip protobuf.zip
RUN cp /tmp/bin/protoc /opt
RUN mv /tmp/include /opt

# Install protoc-gen-go
RUN go get github.com/golang/protobuf/protoc-gen-go
RUN cp /go/bin/protoc-gen-go /opt
RUN go get -u github.com/twitchtv/twirp/protoc-gen-twirp
RUN cp /go/bin/protoc-gen-twirp /opt

# Install node

WORKDIR /opt
RUN apt-get install -y nodejs npm
RUN npm install ts-protoc-gen

ENV PATH /opt:$PATH
ENV CODE_DIR /opt/code
WORKDIR /opt/code/liwords