FROM golang

RUN apt-get update && apt-get install -y unzip

ENV PROTOC_VERSION 3.15.8

# add protoc
RUN curl -L -o /tmp/protobuf.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-aarch_64.zip
WORKDIR /tmp/
RUN unzip protobuf.zip && cp /tmp/bin/protoc /opt && mv /tmp/include /opt

# Install protoc-gen-go
RUN go get github.com/golang/protobuf/protoc-gen-go \
    && cp /go/bin/protoc-gen-go /opt \
    && go get github.com/twitchtv/twirp/protoc-gen-twirp \
    && cp /go/bin/protoc-gen-twirp /opt

# Install node

WORKDIR /opt
RUN apt-get install -y nodejs npm && npm install ts-protoc-gen

ENV PATH /opt:$PATH
ENV CODE_DIR /opt/code
WORKDIR /opt/code/liwords