FROM golang:latest as base

RUN apt-get update && apt-get install -y curl

# protobuf executables:
WORKDIR /tmp
RUN curl -L https://github.com/bufbuild/buf/releases/download/v1.9.0/buf-Linux-x86_64  --output buf
RUN chmod +x buf

# Install protoc-gen-go
RUN go install github.com/golang/protobuf/protoc-gen-go@latest \
    && go install github.com/twitchtv/twirp/protoc-gen-twirp@latest

# Detect arch for migrate
ENV ARCH="$(uname -m | sed 's/aarch64/aarch_64/g')"
RUN echo "Detected arch ${ARCH}"
# migrate:

ENV MIGRATE_VERSION v4.15.2
ENV MIGRATE_ARCH="$(case ${ARCH} in \"aarch_64\") echo \"arm64\" ;; \"x86_64\") echo \"amd64\";; *) echo \"invalid architecture\" ;; esac;)"

RUN echo "Fetching from URL: https://github.com/golang-migrate/migrate/releases/download/${MIGRATE_VERSION}/migrate.linux-$(eval echo ${MIGRATE_ARCH}).tar.gz"

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/${MIGRATE_VERSION}/migrate.linux-$(eval echo ${MIGRATE_ARCH}).tar.gz | tar xvz

RUN mv /tmp/migrate /opt
RUN mv /tmp/buf /opt

FROM node:latest

RUN useradd unprivileged

WORKDIR /opt
RUN npm install @bufbuild/protoc-gen-es
RUN npm install @bufbuild/protoc-gen-connect-web

COPY --from=base /go/bin/protoc-gen-go /opt
COPY --from=base /go/bin/protoc-gen-twirp /opt
COPY --from=base /opt/buf /opt
COPY --from=base /opt/migrate /opt

ENV PATH /opt:$PATH

WORKDIR /opt/code/liwords