FROM golang:alpine as build-env

RUN mkdir /opt/program
WORKDIR /opt/program

RUN apk update
RUN apk add build-base ca-certificates git

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

WORKDIR /opt/program/cmd/maintenance

ARG BUILD_HASH=unknown
ARG BUILD_DATE=unknown

RUN go build -o maintenance -ldflags "-X=main.BuildDate=${BUILD_DATE} -X=main.BuildHash=${BUILD_HASH}"
### This Dockerfile is for an ECS task that performs periodic maintenance.

# Build minimal image:
FROM alpine
COPY --from=build-env /opt/program/cmd/maintenance/maintenance /opt/maintenance
WORKDIR /opt
CMD ["/opt/maintenance"]

LABEL org.opencontainers.image.source https://github.com/domino14/liwords