tournament_id: 9NfEjqDtyaZHTJjxLkpdep
division_name: "NWL"
gibson_spread: [250, 200]
control_loss_threshold: 0.25
hopefulness_threshold: [0, 0.1, 0.05, 0.02, 0.01]
division_sims: 100000
control_loss_sims: 10000
control_loss_activation_round: 7
place_prizes: 1