AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EventBridge Ruleliwords-daily-maintenance
Resources:
  DailyMaintenanceRule:
    Type: AWS::Events::Rule
    Properties:
      Name: liwords-daily-maintenance
      ScheduleExpression: cron(00 17 * * ? *)
      State: ENABLED
      Description: Daily maintenance for liwords. Only daily tasks should go here.
      EventBusName: default
      Targets:
        - Id: !Sub "${AWS::StackName}-DailyMaintenanceTarget"
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/woogles-prod
          RoleArn:
            Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ecsEventsRole
          Input:
            Fn::Sub: |-
              {
                  "taskRoleArn": "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole",
                  "containerOverrides": [
                      {
                          "name": "maintenance",
                          "command": [
                              "/opt/maintenance",
                              "integrations-refresher,partition-creator,cancelled-games-cleanup"
                          ]
                      }
                  ]
              }
          EcsParameters:
            TaskDefinitionArn:
              Fn::Sub: >-
                arn:aws:ecs:us-east-2:${AWS::AccountId}:task-definition/liwords-maintenance
            TaskCount: 1
            LaunchType: EC2
            EnableECSManagedTags: false
            EnableExecuteCommand: false
Parameters: {}
