AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition for Liwords Database Migrations

Parameters:
  TaskExecutionRoleArn:
    Type: String
    Description: ARN of the ECS task execution role (must have SSM read permissions)
    Default: arn:aws:iam::ACCOUNT_ID:role/ecsTaskExecutionRole

  DockerImage:
    Type: String
    Description: Docker image for the liwords-api container
    Default: ghcr.io/woogles-io/liwords-api:latest

  DBHostParameter:
    Type: String
    Description: SSM Parameter name for database host
    Default: /liwords/prod/db/host

  DBPortParameter:
    Type: String
    Description: SSM Parameter name for database port
    Default: /liwords/prod/db/port

  DBUserParameter:
    Type: String
    Description: SSM Parameter name for database user
    Default: /liwords/prod/db/user

  DBPasswordParameter:
    Type: String
    Description: SSM Parameter name for database password (SecureString)
    Default: /liwords/prod/db/password

  DBNameParameter:
    Type: String
    Description: SSM Parameter name for database name
    Default: /liwords/prod/db/name

  DBSSLModeParameter:
    Type: String
    Description: SSM Parameter name for database SSL mode
    Default: /liwords/prod/db/sslmode

Resources:
  MigrationTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: liwords-db-migration
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      ContainerDefinitions:
        - Name: db-migration
          Image: !Ref DockerImage
          Essential: true
          Command:
            - /opt/liwords-api
            - -db-migrations-path=/opt/db/migrations
            - -run-migrations=true
            - -quit-after-migration=true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/liwords-db-migration
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: migration
          Secrets:
            - Name: DB_HOST
              ValueFrom: !Ref DBHostParameter
            - Name: DB_PORT
              ValueFrom: !Ref DBPortParameter
            - Name: DB_USER
              ValueFrom: !Ref DBUserParameter
            - Name: DB_PASSWORD
              ValueFrom: !Ref DBPasswordParameter
            - Name: DB_NAME
              ValueFrom: !Ref DBNameParameter
            - Name: DB_SSL_MODE
              ValueFrom: !Ref DBSSLModeParameter
          Environment:
            - Name: DB_MIGRATIONS_PATH
              Value: /opt/db/migrations

  MigrationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/liwords-db-migration
      RetentionInDays: 7

Outputs:
  TaskDefinitionArn:
    Description: ARN of the migration task definition
    Value: !Ref MigrationTaskDefinition
    Export:
      Name: !Sub '${AWS::StackName}-TaskDefinitionArn'

  TaskDefinitionFamily:
    Description: Family name of the task definition
    Value: liwords-db-migration
    Export:
      Name: !Sub '${AWS::StackName}-TaskDefinitionFamily'

  LogGroupName:
    Description: CloudWatch Logs group for migration task
    Value: !Ref MigrationLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroupName'
