AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for all Liwords maintenance EventBridge scheduled tasks
Resources:
  HourlyMaintenanceRule:
    Type: AWS::Events::Rule
    Properties:
      Name: liwords-hourly-maintenance
      ScheduleExpression: cron(4 * * * ? *)
      State: ENABLED
      Description: Hourly maintenance for liwords. Runs blog RSS updater, badge updater, and league hourly runner.
      EventBusName: default
      Targets:
        - Id: !Sub "${AWS::StackName}-HourlyMaintenanceTarget"
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/woogles-prod
          RoleArn:
            Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ecsEventsRole
          Input:
            Fn::Sub: |-
              {
                  "taskRoleArn": "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole",
                  "containerOverrides": [
                      {
                          "name": "maintenance",
                          "command": [
                              "/opt/maintenance",
                              "blogrss-updater,sub-badge-updater,league-hourly-runner"
                          ]
                      }
                  ]
              }
          EcsParameters:
            TaskDefinitionArn:
              Fn::Sub: >-
                arn:aws:ecs:us-east-2:${AWS::AccountId}:task-definition/liwords-maintenance
            TaskCount: 1
            LaunchType: EC2
            EnableECSManagedTags: false
            EnableExecuteCommand: false

  DailyMidnightMaintenanceRule:
    Type: AWS::Events::Rule
    Properties:
      Name: liwords-daily-midnight-maintenance
      ScheduleExpression: cron(0 5 * * ? *)
      State: ENABLED
      Description: Daily midnight (US Eastern) maintenance for liwords. Runs integrations refresh, game cleanup, session cleanup, and user cleanup. League tasks now handled by hourly runner.
      EventBusName: default
      Targets:
        - Id: !Sub "${AWS::StackName}-DailyMidnightTarget"
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/woogles-prod
          RoleArn:
            Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ecsEventsRole
          Input:
            Fn::Sub: |-
              {
                  "taskRoleArn": "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole",
                  "containerOverrides": [
                      {
                          "name": "maintenance",
                          "command": [
                              "/opt/maintenance",
                              "integrations-refresher,cancelled-games-cleanup,monitoring-streams-cleanup,expired-sessions-cleanup,unverified-users-cleanup,league-unstarted-game-reminder"
                          ]
                      }
                  ]
              }
          EcsParameters:
            TaskDefinitionArn:
              Fn::Sub: >-
                arn:aws:ecs:us-east-2:${AWS::AccountId}:task-definition/liwords-maintenance
            TaskCount: 1
            LaunchType: EC2
            EnableECSManagedTags: false
            EnableExecuteCommand: false

  # Note: Daily8amMaintenanceRule has been replaced by the hourly runner.
  # The league-hourly-runner now checks all leagues for tasks that need to run
  # based on their actual start/end dates, not a fixed 8am Eastern schedule.
  # Old 8am runner kept as disabled for rollback purposes if needed.
  Daily8amMaintenanceRule:
    Type: AWS::Events::Rule
    Properties:
      Name: liwords-daily-8am-maintenance
      ScheduleExpression: cron(0 13 * * ? *)
      State: DISABLED
      Description: "[DEPRECATED - replaced by hourly runner] Daily 8am (US Eastern) maintenance. League tasks now handled by league-hourly-runner."
      EventBusName: default
      Targets:
        - Id: !Sub "${AWS::StackName}-Daily8amTarget"
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/woogles-prod
          RoleArn:
            Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ecsEventsRole
          Input:
            Fn::Sub: |-
              {
                  "taskRoleArn": "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole",
                  "containerOverrides": [
                      {
                          "name": "maintenance",
                          "command": [
                              "/opt/maintenance",
                              "league-morning-runner"
                          ]
                      }
                  ]
              }
          EcsParameters:
            TaskDefinitionArn:
              Fn::Sub: >-
                arn:aws:ecs:us-east-2:${AWS::AccountId}:task-definition/liwords-maintenance
            TaskCount: 1
            LaunchType: EC2
            EnableECSManagedTags: false
            EnableExecuteCommand: false

Parameters: {}
