AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for all Liwords maintenance EventBridge scheduled tasks
Resources:
  # IAM Role for maintenance tasks - allows container code to access AWS services
  MaintenanceTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: liwordsMaintenanceTaskRole
      Description: Task role for liwords maintenance tasks - grants SES permissions for email sending
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SESSendEmailPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: '*'
      Tags:
        - Key: Application
          Value: liwords
        - Key: Component
          Value: maintenance
  HourlyMaintenanceRule:
    Type: AWS::Events::Rule
    Properties:
      Name: liwords-hourly-maintenance
      ScheduleExpression: cron(1 * * * ? *)
      State: ENABLED
      Description: Hourly maintenance for liwords. Runs blog RSS updater, badge updater, and league hourly runner.
      EventBusName: default
      Targets:
        - Id: !Sub "${AWS::StackName}-HourlyMaintenanceTarget"
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/woogles-prod
          RoleArn:
            Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ecsEventsRole
          Input:
            Fn::Sub: |-
              {
                  "containerOverrides": [
                      {
                          "name": "maintenance",
                          "command": [
                              "/opt/maintenance",
                              "blogrss-updater,sub-badge-updater,league-hourly-runner"
                          ]
                      }
                  ]
              }
          EcsParameters:
            TaskDefinitionArn:
              Fn::Sub: >-
                arn:aws:ecs:us-east-2:${AWS::AccountId}:task-definition/liwords-maintenance
            TaskCount: 1
            LaunchType: EC2
            EnableECSManagedTags: false
            EnableExecuteCommand: false

  DailyMidnightMaintenanceRule:
    Type: AWS::Events::Rule
    Properties:
      Name: liwords-daily-midnight-maintenance
      ScheduleExpression: cron(0 5 * * ? *)
      State: ENABLED
      Description: Daily midnight (US Eastern) maintenance for liwords. Runs integrations refresh, game cleanup, session cleanup, and user cleanup. League tasks now handled by hourly runner.
      EventBusName: default
      Targets:
        - Id: !Sub "${AWS::StackName}-DailyMidnightTarget"
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/woogles-prod
          RoleArn:
            Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ecsEventsRole
          Input:
            Fn::Sub: |-
              {
                  "containerOverrides": [
                      {
                          "name": "maintenance",
                          "command": [
                              "/opt/maintenance",
                              "integrations-refresher,cancelled-games-cleanup,monitoring-streams-cleanup,expired-sessions-cleanup,unverified-users-cleanup,league-unstarted-game-reminder"
                          ]
                      }
                  ]
              }
          EcsParameters:
            TaskDefinitionArn:
              Fn::Sub: >-
                arn:aws:ecs:us-east-2:${AWS::AccountId}:task-definition/liwords-maintenance
            TaskCount: 1
            LaunchType: EC2
            EnableECSManagedTags: false
            EnableExecuteCommand: false

Parameters: {}
