#!/usr/bin/env python3
"""Build reporting/assets/fonts/woogles-fonts.css - the Woogles web fonts,
base64-inlined, for the monthly report PDF.

The PDF is printed by headless Chrome. Linking Google Fonts there is a race:
the print pass has no guaranteed network wait, so a slow font silently falls
back to Helvetica and the report ships un-branded. Inlining the faces as data:
URIs makes the print deterministic and the PDF self-contained.

Run by hand when the fonts need refreshing; the generated CSS is committed:
    python3 reporting/scripts/fetch_report_fonts.py

Families match liwords-ui/src/base.scss - Mulish ($font-default) and Fjalla One
($font-deco). Both are SIL Open Font License, so redistributing them here is
fine. Only the latin subset is kept; the report has no Cyrillic or Vietnamese
text and the other subsets triple the size for nothing.
"""
import base64
import re
import sys
from pathlib import Path

# requests, not urllib: urllib.request fails CERTIFICATE_VERIFY_FAILED against
# fonts.googleapis.com on this Mac's python.org 3.12 (no local issuer certs).
import requests

CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Mulish:wght@400;700;800&family=Fjalla+One&display=swap")
# Google serves woff2 only to a UA it believes supports it.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
OUT = Path(__file__).resolve().parent.parent / "assets" / "fonts" / "woogles-fonts.css"


def fetch(url):
    r = requests.get(url, headers={"User-Agent": UA}, timeout=30)
    r.raise_for_status()
    return r.content


def main():
    css = fetch(CSS_URL).decode()
    blocks = re.findall(r"@font-face\s*\{.*?\}", css, flags=re.S)
    kept = []
    for block in blocks:
        # The latin subset is the one covering basic ASCII; every other subset
        # block declares a range that starts well above it.
        if "U+0000-00FF" not in block:
            continue
        m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not m:
            continue
        b64 = base64.b64encode(fetch(m.group(1))).decode()
        kept.append(block.replace(
            m.group(1), f"data:font/woff2;base64,{b64}"))

    if len(kept) < 4:
        print(f"ERROR: expected 4 latin faces, got {len(kept)}", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* Generated by scripts/fetch_report_fonts.py - do not edit by hand.\n"
        "   Mulish and Fjalla One, SIL Open Font License, latin subset only. */\n"
        + "\n".join(kept) + "\n")
    print(f"{OUT} ({OUT.stat().st_size // 1024} KB, {len(kept)} faces)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
