FROM liwords-builder as build-env

WORKDIR /opt/program/cmd/puzzlegen

ARG BUILD_HASH=unknown
ARG BUILD_DATE=unknown

RUN go build -o puzzle-generator -ldflags "-X=main.BuildDate=${BUILD_DATE} -X=main.BuildHash=${BUILD_HASH}"
### This Dockerfile is for an ECS task that generates puzzles.

# Build minimal image:
FROM debian:latest
COPY --from=build-env /opt/program/cmd/puzzlegen/puzzle-generator /opt/puzzle-generator
WORKDIR /opt
CMD ["/opt/puzzle-generator"]

LABEL org.opencontainers.image.source https://github.com/woogles-io/liwords