FROM liwords-builder AS build-env

WORKDIR /opt/program/cmd/socketsrv

ARG BUILD_HASH=unknown
ARG BUILD_DATE=unknown

RUN go build -ldflags  "-X=main.BuildDate=${BUILD_DATE} -X=main.BuildHash=${BUILD_HASH}"

# Build minimal image:
FROM debian:latest
COPY --from=build-env /opt/program/cmd/socketsrv/socketsrv /opt/socketsrv
EXPOSE 8087

WORKDIR /opt
CMD ["./socketsrv"]

LABEL org.opencontainers.image.source https://github.com/woogles-io/liwords
