FROM liwords-builder AS build-env

WORKDIR /opt/program/cmd/liwords-api

ARG BUILD_HASH=unknown
ARG BUILD_DATE=unknown

RUN go build -ldflags  "-X=main.BuildDate=${BUILD_DATE} -X=main.BuildHash=${BUILD_HASH}"

# Build minimal image:
FROM debian:latest
COPY --from=build-env /opt/program/cmd/liwords-api/liwords-api /opt/liwords-api
COPY --from=build-env /opt/program/db /opt/db

RUN apt-get update && apt-get install -y curl

EXPOSE 8001

WORKDIR /opt
CMD ["./liwords-api"]

LABEL org.opencontainers.image.source https://github.com/woogles-io/liwords
