FROM liwords-builder as build-env

WORKDIR /opt/program/cmd/maintenance

ARG BUILD_HASH=unknown
ARG BUILD_DATE=unknown

RUN go build -o maintenance -ldflags "-X=main.BuildDate=${BUILD_DATE} -X=main.BuildHash=${BUILD_HASH}"
### This Dockerfile is for an ECS task that performs periodic maintenance.

# Build minimal image:
FROM debian:latest
COPY --from=build-env /opt/program/cmd/maintenance/maintenance /opt/maintenance

RUN apt-get update && apt-get install -y ca-certificates

WORKDIR /opt
CMD ["/opt/maintenance"]

LABEL org.opencontainers.image.source https://github.com/woogles-io/liwords