FROM public.ecr.aws/sam/build-python3.9

RUN yum install -y cairo-devel cairo pkgconfig open-sans-fonts

# WORKDIR /app
# COPY . /app

# RUN pip install --no-cache-dir -r /app/src/requirements.txt

# # Run main.py when the container launches
# CMD ["python", "src/main.py"]