// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: api/proto/puzzle_service/puzzle_service.proto

package puzzle_service

import (
	macondo "github.com/domino14/macondo/gen/api/proto/macondo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PuzzleStatus int32

const (
	PuzzleStatus_UNANSWERED PuzzleStatus = 0
	PuzzleStatus_CORRECT    PuzzleStatus = 1
	PuzzleStatus_INCORRECT  PuzzleStatus = 2
)

// Enum value maps for PuzzleStatus.
var (
	PuzzleStatus_name = map[int32]string{
		0: "UNANSWERED",
		1: "CORRECT",
		2: "INCORRECT",
	}
	PuzzleStatus_value = map[string]int32{
		"UNANSWERED": 0,
		"CORRECT":    1,
		"INCORRECT":  2,
	}
)

func (x PuzzleStatus) Enum() *PuzzleStatus {
	p := new(PuzzleStatus)
	*p = x
	return p
}

func (x PuzzleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PuzzleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_puzzle_service_puzzle_service_proto_enumTypes[0].Descriptor()
}

func (PuzzleStatus) Type() protoreflect.EnumType {
	return &file_api_proto_puzzle_service_puzzle_service_proto_enumTypes[0]
}

func (x PuzzleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PuzzleStatus.Descriptor instead.
func (PuzzleStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP(), []int{0}
}

type RandomUnansweredPuzzleIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lexicon string `protobuf:"bytes,1,opt,name=lexicon,proto3" json:"lexicon,omitempty"`
}

func (x *RandomUnansweredPuzzleIdRequest) Reset() {
	*x = RandomUnansweredPuzzleIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomUnansweredPuzzleIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomUnansweredPuzzleIdRequest) ProtoMessage() {}

func (x *RandomUnansweredPuzzleIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomUnansweredPuzzleIdRequest.ProtoReflect.Descriptor instead.
func (*RandomUnansweredPuzzleIdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP(), []int{0}
}

func (x *RandomUnansweredPuzzleIdRequest) GetLexicon() string {
	if x != nil {
		return x.Lexicon
	}
	return ""
}

type RandomUnansweredPuzzleIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PuzzleId string `protobuf:"bytes,1,opt,name=puzzle_id,json=puzzleId,proto3" json:"puzzle_id,omitempty"`
}

func (x *RandomUnansweredPuzzleIdResponse) Reset() {
	*x = RandomUnansweredPuzzleIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomUnansweredPuzzleIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomUnansweredPuzzleIdResponse) ProtoMessage() {}

func (x *RandomUnansweredPuzzleIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomUnansweredPuzzleIdResponse.ProtoReflect.Descriptor instead.
func (*RandomUnansweredPuzzleIdResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP(), []int{1}
}

func (x *RandomUnansweredPuzzleIdResponse) GetPuzzleId() string {
	if x != nil {
		return x.PuzzleId
	}
	return ""
}

type PuzzleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PuzzleId string `protobuf:"bytes,1,opt,name=puzzle_id,json=puzzleId,proto3" json:"puzzle_id,omitempty"`
}

func (x *PuzzleRequest) Reset() {
	*x = PuzzleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuzzleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuzzleRequest) ProtoMessage() {}

func (x *PuzzleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuzzleRequest.ProtoReflect.Descriptor instead.
func (*PuzzleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP(), []int{2}
}

func (x *PuzzleRequest) GetPuzzleId() string {
	if x != nil {
		return x.PuzzleId
	}
	return ""
}

type PuzzleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History    *macondo.GameHistory `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"`
	BeforeText string               `protobuf:"bytes,2,opt,name=before_text,json=beforeText,proto3" json:"before_text,omitempty"`
	Attempts   int32                `protobuf:"varint,3,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Status     PuzzleStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=puzzle_service.PuzzleStatus" json:"status,omitempty"`
}

func (x *PuzzleResponse) Reset() {
	*x = PuzzleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuzzleResponse) ProtoMessage() {}

func (x *PuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuzzleResponse.ProtoReflect.Descriptor instead.
func (*PuzzleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP(), []int{3}
}

func (x *PuzzleResponse) GetHistory() *macondo.GameHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *PuzzleResponse) GetBeforeText() string {
	if x != nil {
		return x.BeforeText
	}
	return ""
}

func (x *PuzzleResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *PuzzleResponse) GetStatus() PuzzleStatus {
	if x != nil {
		return x.Status
	}
	return PuzzleStatus_UNANSWERED
}

type SubmissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PuzzleId     string             `protobuf:"bytes,1,opt,name=puzzle_id,json=puzzleId,proto3" json:"puzzle_id,omitempty"`
	Answer       *macondo.GameEvent `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	ShowSolution bool               `protobuf:"varint,3,opt,name=show_solution,json=showSolution,proto3" json:"show_solution,omitempty"`
}

func (x *SubmissionRequest) Reset() {
	*x = SubmissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionRequest) ProtoMessage() {}

func (x *SubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionRequest.ProtoReflect.Descriptor instead.
func (*SubmissionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubmissionRequest) GetPuzzleId() string {
	if x != nil {
		return x.PuzzleId
	}
	return ""
}

func (x *SubmissionRequest) GetAnswer() *macondo.GameEvent {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *SubmissionRequest) GetShowSolution() bool {
	if x != nil {
		return x.ShowSolution
	}
	return false
}

type SubmissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIsCorrect bool               `protobuf:"varint,1,opt,name=user_is_correct,json=userIsCorrect,proto3" json:"user_is_correct,omitempty"`
	CorrectAnswer *macondo.GameEvent `protobuf:"bytes,2,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	GameId        string             `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	AfterText     string             `protobuf:"bytes,4,opt,name=after_text,json=afterText,proto3" json:"after_text,omitempty"`
	Attempts      int32              `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
}

func (x *SubmissionResponse) Reset() {
	*x = SubmissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionResponse) ProtoMessage() {}

func (x *SubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionResponse.ProtoReflect.Descriptor instead.
func (*SubmissionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubmissionResponse) GetUserIsCorrect() bool {
	if x != nil {
		return x.UserIsCorrect
	}
	return false
}

func (x *SubmissionResponse) GetCorrectAnswer() *macondo.GameEvent {
	if x != nil {
		return x.CorrectAnswer
	}
	return nil
}

func (x *SubmissionResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SubmissionResponse) GetAfterText() string {
	if x != nil {
		return x.AfterText
	}
	return ""
}

func (x *SubmissionResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type PuzzleVoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PuzzleId string `protobuf:"bytes,1,opt,name=puzzle_id,json=puzzleId,proto3" json:"puzzle_id,omitempty"`
	Vote     int32  `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
}

func (x *PuzzleVoteRequest) Reset() {
	*x = PuzzleVoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuzzleVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuzzleVoteRequest) ProtoMessage() {}

func (x *PuzzleVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuzzleVoteRequest.ProtoReflect.Descriptor instead.
func (*PuzzleVoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP(), []int{6}
}

func (x *PuzzleVoteRequest) GetPuzzleId() string {
	if x != nil {
		return x.PuzzleId
	}
	return ""
}

func (x *PuzzleVoteRequest) GetVote() int32 {
	if x != nil {
		return x.Vote
	}
	return 0
}

type PuzzleVoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PuzzleVoteResponse) Reset() {
	*x = PuzzleVoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuzzleVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuzzleVoteResponse) ProtoMessage() {}

func (x *PuzzleVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuzzleVoteResponse.ProtoReflect.Descriptor instead.
func (*PuzzleVoteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP(), []int{7}
}

var File_api_proto_puzzle_service_puzzle_service_proto protoreflect.FileDescriptor

var file_api_proto_puzzle_service_puzzle_service_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x27, 0x6d, 0x61, 0x63, 0x6f, 0x6e, 0x64, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x63, 0x6f, 0x6e, 0x64, 0x6f, 0x2f, 0x6d, 0x61, 0x63, 0x6f, 0x6e,
	0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x1f, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x55, 0x6e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64, 0x50, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x65, 0x78, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x65,
	0x78, 0x69, 0x63, 0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x20, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x55,
	0x6e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75,
	0x7a, 0x7a, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0d, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x49, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x63, 0x6f, 0x6e,
	0x64, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x07,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x65, 0x66, 0x6f, 0x72,
	0x65, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x65,
	0x66, 0x6f, 0x72, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x81, 0x01, 0x0a, 0x11, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6d, 0x61, 0x63, 0x6f, 0x6e, 0x64, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x68, 0x6f,
	0x77, 0x5f, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xcb,
	0x01, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x73,
	0x5f, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x73, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x12, 0x39, 0x0a,
	0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x63, 0x6f, 0x6e, 0x64, 0x6f, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65,
	0x63, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x66, 0x74, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x22, 0x44, 0x0a, 0x11,
	0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x6f,
	0x74, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x56, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x3a, 0x0a, 0x0c, 0x50, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x4e, 0x41, 0x4e,
	0x53, 0x57, 0x45, 0x52, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x52, 0x52,
	0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x43, 0x4f, 0x52, 0x52, 0x45,
	0x43, 0x54, 0x10, 0x02, 0x32, 0x94, 0x03, 0x0a, 0x0d, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x87, 0x01, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x52, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x55, 0x6e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64, 0x50, 0x75,
	0x7a, 0x7a, 0x6c, 0x65, 0x49, 0x64, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2f, 0x2e,
	0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x55, 0x6e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64, 0x50,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30,
	0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x55, 0x6e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64,
	0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x12, 0x1d, 0x2e,
	0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x75,
	0x7a, 0x7a, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0c,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x70,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65,
	0x56, 0x6f, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x56, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x56,
	0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x6d, 0x69, 0x6e, 0x6f,
	0x31, 0x34, 0x2f, 0x6c, 0x69, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_puzzle_service_puzzle_service_proto_rawDescOnce sync.Once
	file_api_proto_puzzle_service_puzzle_service_proto_rawDescData = file_api_proto_puzzle_service_puzzle_service_proto_rawDesc
)

func file_api_proto_puzzle_service_puzzle_service_proto_rawDescGZIP() []byte {
	file_api_proto_puzzle_service_puzzle_service_proto_rawDescOnce.Do(func() {
		file_api_proto_puzzle_service_puzzle_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_puzzle_service_puzzle_service_proto_rawDescData)
	})
	return file_api_proto_puzzle_service_puzzle_service_proto_rawDescData
}

var file_api_proto_puzzle_service_puzzle_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_puzzle_service_puzzle_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_puzzle_service_puzzle_service_proto_goTypes = []interface{}{
	(PuzzleStatus)(0),                        // 0: puzzle_service.PuzzleStatus
	(*RandomUnansweredPuzzleIdRequest)(nil),  // 1: puzzle_service.RandomUnansweredPuzzleIdRequest
	(*RandomUnansweredPuzzleIdResponse)(nil), // 2: puzzle_service.RandomUnansweredPuzzleIdResponse
	(*PuzzleRequest)(nil),                    // 3: puzzle_service.PuzzleRequest
	(*PuzzleResponse)(nil),                   // 4: puzzle_service.PuzzleResponse
	(*SubmissionRequest)(nil),                // 5: puzzle_service.SubmissionRequest
	(*SubmissionResponse)(nil),               // 6: puzzle_service.SubmissionResponse
	(*PuzzleVoteRequest)(nil),                // 7: puzzle_service.PuzzleVoteRequest
	(*PuzzleVoteResponse)(nil),               // 8: puzzle_service.PuzzleVoteResponse
	(*macondo.GameHistory)(nil),              // 9: macondo.GameHistory
	(*macondo.GameEvent)(nil),                // 10: macondo.GameEvent
}
var file_api_proto_puzzle_service_puzzle_service_proto_depIdxs = []int32{
	9,  // 0: puzzle_service.PuzzleResponse.history:type_name -> macondo.GameHistory
	0,  // 1: puzzle_service.PuzzleResponse.status:type_name -> puzzle_service.PuzzleStatus
	10, // 2: puzzle_service.SubmissionRequest.answer:type_name -> macondo.GameEvent
	10, // 3: puzzle_service.SubmissionResponse.correct_answer:type_name -> macondo.GameEvent
	1,  // 4: puzzle_service.PuzzleService.GetRandomUnansweredPuzzleIdForUser:input_type -> puzzle_service.RandomUnansweredPuzzleIdRequest
	3,  // 5: puzzle_service.PuzzleService.GetPuzzle:input_type -> puzzle_service.PuzzleRequest
	5,  // 6: puzzle_service.PuzzleService.SubmitAnswer:input_type -> puzzle_service.SubmissionRequest
	7,  // 7: puzzle_service.PuzzleService.SetPuzzleVote:input_type -> puzzle_service.PuzzleVoteRequest
	2,  // 8: puzzle_service.PuzzleService.GetRandomUnansweredPuzzleIdForUser:output_type -> puzzle_service.RandomUnansweredPuzzleIdResponse
	4,  // 9: puzzle_service.PuzzleService.GetPuzzle:output_type -> puzzle_service.PuzzleResponse
	6,  // 10: puzzle_service.PuzzleService.SubmitAnswer:output_type -> puzzle_service.SubmissionResponse
	8,  // 11: puzzle_service.PuzzleService.SetPuzzleVote:output_type -> puzzle_service.PuzzleVoteResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_puzzle_service_puzzle_service_proto_init() }
func file_api_proto_puzzle_service_puzzle_service_proto_init() {
	if File_api_proto_puzzle_service_puzzle_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomUnansweredPuzzleIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomUnansweredPuzzleIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuzzleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuzzleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuzzleVoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_puzzle_service_puzzle_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuzzleVoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_puzzle_service_puzzle_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_puzzle_service_puzzle_service_proto_goTypes,
		DependencyIndexes: file_api_proto_puzzle_service_puzzle_service_proto_depIdxs,
		EnumInfos:         file_api_proto_puzzle_service_puzzle_service_proto_enumTypes,
		MessageInfos:      file_api_proto_puzzle_service_puzzle_service_proto_msgTypes,
	}.Build()
	File_api_proto_puzzle_service_puzzle_service_proto = out.File
	file_api_proto_puzzle_service_puzzle_service_proto_rawDesc = nil
	file_api_proto_puzzle_service_puzzle_service_proto_goTypes = nil
	file_api_proto_puzzle_service_puzzle_service_proto_depIdxs = nil
}
