// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_turns.sql

package models

import (
	"context"
)

const appendGameTurn = `-- name: AppendGameTurn :exec
INSERT INTO game_turns (game_uuid, turn_idx, event)
VALUES ($1, $2, $3)
`

type AppendGameTurnParams struct {
	GameUuid string
	TurnIdx  int32
	Event    []byte
}

func (q *Queries) AppendGameTurn(ctx context.Context, arg AppendGameTurnParams) error {
	_, err := q.db.Exec(ctx, appendGameTurn, arg.GameUuid, arg.TurnIdx, arg.Event)
	return err
}

const countGameTurns = `-- name: CountGameTurns :one
SELECT COUNT(*)::int4 FROM game_turns WHERE game_uuid = $1
`

func (q *Queries) CountGameTurns(ctx context.Context, gameUuid string) (int32, error) {
	row := q.db.QueryRow(ctx, countGameTurns, gameUuid)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteGameTurns = `-- name: DeleteGameTurns :exec
DELETE FROM game_turns WHERE game_uuid = $1
`

func (q *Queries) DeleteGameTurns(ctx context.Context, gameUuid string) error {
	_, err := q.db.Exec(ctx, deleteGameTurns, gameUuid)
	return err
}

const getGameTurns = `-- name: GetGameTurns :many
SELECT turn_idx, event FROM game_turns
WHERE game_uuid = $1
ORDER BY turn_idx ASC
`

type GetGameTurnsRow struct {
	TurnIdx int32
	Event   []byte
}

func (q *Queries) GetGameTurns(ctx context.Context, gameUuid string) ([]GetGameTurnsRow, error) {
	rows, err := q.db.Query(ctx, getGameTurns, gameUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameTurnsRow
	for rows.Next() {
		var i GetGameTurnsRow
		if err := rows.Scan(&i.TurnIdx, &i.Event); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastGameTurn = `-- name: GetLastGameTurn :one
SELECT turn_idx, event FROM game_turns
WHERE game_uuid = $1
ORDER BY turn_idx DESC
LIMIT 1
`

type GetLastGameTurnRow struct {
	TurnIdx int32
	Event   []byte
}

func (q *Queries) GetLastGameTurn(ctx context.Context, gameUuid string) (GetLastGameTurnRow, error) {
	row := q.db.QueryRow(ctx, getLastGameTurn, gameUuid)
	var i GetLastGameTurnRow
	err := row.Scan(&i.TurnIdx, &i.Event)
	return i, err
}
