// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_turns.sql

package models

import (
	"context"
)

const appendGameTurn = `-- name: AppendGameTurn :exec
INSERT INTO game_turns (game_uuid, turn_idx, event)
VALUES ($1, $2, $3)
`

type AppendGameTurnParams struct {
	GameUuid string
	TurnIdx  int32
	Event    []byte
}

func (q *Queries) AppendGameTurn(ctx context.Context, arg AppendGameTurnParams) error {
	_, err := q.db.Exec(ctx, appendGameTurn, arg.GameUuid, arg.TurnIdx, arg.Event)
	return err
}

const appendGameTurns = `-- name: AppendGameTurns :exec
INSERT INTO game_turns (game_uuid, turn_idx, event)
SELECT $1, ($2::int4 + t.ord::int4 - 1), t.evt
FROM unnest($3::jsonb[]) WITH ORDINALITY AS t(evt, ord)
`

type AppendGameTurnsParams struct {
	GameUuid string
	StartIdx int32
	Events   [][]byte
}

// Append a whole move's events in one statement.
//
// NOT STANDARD SQL -- read this before editing it.
//
// `unnest(array) WITH ORDINALITY AS t(evt, ord)` turns one array parameter into
// one row per element, with `ord` counting 1, 2, 3... So passing three events
// with start_idx = 7 inserts turn_idx 7, 8 and 9. Postgres-specific, and the
// reason it is worth the strangeness is round trips: a move can produce three
// events (six scoreless turns writes a PASS and two END_RACK_PENALTY events),
// and this writes them in one call instead of three while a per-game advisory
// lock is held.
//
// Three plain INSERTs inside the same transaction would be equally *correct* --
// a transaction is what makes a move atomic, not this statement. This is only
// fewer round trips. If it ever gets in the way, replacing it with a loop of
// AppendGameTurn inside the same transaction loses nothing but latency.
//
// The indices are derived from `ord` rather than passed in as a second array,
// because a move's events are always consecutive from start_idx. A parallel
// array of indices would add a way for the indices and the events to disagree.
//
// sqlc note: the arithmetic must be parenthesised and use sqlc.arg(), or sqlc
// silently rewrites the expression -- it emitted `($2::int4 - 1)`, dropping the
// ordinal entirely, which would insert every event at the same index. Check the
// generated SQL in pkg/stores/models/game_turns.sql.go after touching this.
func (q *Queries) AppendGameTurns(ctx context.Context, arg AppendGameTurnsParams) error {
	_, err := q.db.Exec(ctx, appendGameTurns, arg.GameUuid, arg.StartIdx, arg.Events)
	return err
}

const countGameTurns = `-- name: CountGameTurns :one
SELECT COUNT(*)::int4 FROM game_turns WHERE game_uuid = $1
`

func (q *Queries) CountGameTurns(ctx context.Context, gameUuid string) (int32, error) {
	row := q.db.QueryRow(ctx, countGameTurns, gameUuid)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteGameTurns = `-- name: DeleteGameTurns :exec
DELETE FROM game_turns WHERE game_uuid = $1
`

func (q *Queries) DeleteGameTurns(ctx context.Context, gameUuid string) error {
	_, err := q.db.Exec(ctx, deleteGameTurns, gameUuid)
	return err
}

const getGameTurns = `-- name: GetGameTurns :many
SELECT turn_idx, event FROM game_turns
WHERE game_uuid = $1
ORDER BY turn_idx ASC
`

type GetGameTurnsRow struct {
	TurnIdx int32
	Event   []byte
}

func (q *Queries) GetGameTurns(ctx context.Context, gameUuid string) ([]GetGameTurnsRow, error) {
	rows, err := q.db.Query(ctx, getGameTurns, gameUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameTurnsRow
	for rows.Next() {
		var i GetGameTurnsRow
		if err := rows.Scan(&i.TurnIdx, &i.Event); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastGameTurn = `-- name: GetLastGameTurn :one
SELECT turn_idx, event FROM game_turns
WHERE game_uuid = $1
ORDER BY turn_idx DESC
LIMIT 1
`

type GetLastGameTurnRow struct {
	TurnIdx int32
	Event   []byte
}

func (q *Queries) GetLastGameTurn(ctx context.Context, gameUuid string) (GetLastGameTurnRow, error) {
	row := q.db.QueryRow(ctx, getLastGameTurn, gameUuid)
	var i GetLastGameTurnRow
	err := row.Scan(&i.TurnIdx, &i.Event)
	return i, err
}
