// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: puzzles.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPuzzleGenerationLog = `-- name: CreatePuzzleGenerationLog :one
INSERT INTO puzzle_generation_logs (request, created_at) VALUES ($1, NOW()) RETURNING id
`

func (q *Queries) CreatePuzzleGenerationLog(ctx context.Context, request []byte) (int64, error) {
	row := q.db.QueryRow(ctx, createPuzzleGenerationLog, request)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPotentialPuzzleGames = `-- name: GetPotentialPuzzleGames :many
SELECT games.uuid FROM games
LEFT JOIN puzzles on puzzles.game_id = games.id
WHERE puzzles.id IS NULL
    AND games.created_at BETWEEN $1 AND $2
    AND (stats->'d1'->'Challenged Phonies'->'t' = '0')
    AND (stats->'d2'->'Challenged Phonies'->'t' = '0')
    AND (stats->'d1'->'Unchallenged Phonies'->'t' = '0')
    AND (stats->'d2'->'Unchallenged Phonies'->'t' = '0')
    AND games.game_request->>'lexicon' = $3::text
    AND (
        games.game_request->'rules'->>'variant_name' = 'classic'
        OR games.game_request->'rules'->>'variant_name' IS NULL
        OR games.game_request->'rules'->>'variant_name' = ''
    )
    -- 0: none, 5: aborted, 7: canceled
    AND game_end_reason not in (0, 5, 7)
    AND type = 0

    ORDER BY games.id DESC
    LIMIT $4 OFFSET $5
`

type GetPotentialPuzzleGamesParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
	Column3     string
	Limit       int32
	Offset      int32
}

func (q *Queries) GetPotentialPuzzleGames(ctx context.Context, arg GetPotentialPuzzleGamesParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getPotentialPuzzleGames,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var uuid pgtype.Text
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPotentialPuzzleGamesAvoidBots = `-- name: GetPotentialPuzzleGamesAvoidBots :many

SELECT games.uuid FROM games
LEFT JOIN puzzles on puzzles.game_id = games.id
WHERE puzzles.id IS NULL
    AND games.created_at BETWEEN $1 AND $2
    AND (stats->'d1'->'Challenged Phonies'->'t' = '0')
    AND (stats->'d2'->'Challenged Phonies'->'t' = '0')
    AND (stats->'d1'->'Unchallenged Phonies'->'t' = '0')
    AND (stats->'d2'->'Unchallenged Phonies'->'t' = '0')

    AND games.game_request->>'lexicon' = $3::text
    AND (
        games.game_request->'rules'->>'variant_name' = 'classic'
        OR games.game_request->'rules'->>'variant_name' IS NULL
        OR games.game_request->'rules'->>'variant_name' = ''
    )
    -- 0: none, 5: aborted, 7: canceled
    AND game_end_reason not in (0, 5, 7)
    AND NOT (quickdata @> '{"pi": [{"is_bot": true}]}'::jsonb)
    AND type = 0

    ORDER BY games.id DESC
    LIMIT $4 OFFSET $5
`

type GetPotentialPuzzleGamesAvoidBotsParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
	Column3     string
	Limit       int32
	Offset      int32
}

// puzzle generation
func (q *Queries) GetPotentialPuzzleGamesAvoidBots(ctx context.Context, arg GetPotentialPuzzleGamesAvoidBotsParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getPotentialPuzzleGamesAvoidBots,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var uuid pgtype.Text
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPuzzleDBIDFromUUID = `-- name: GetPuzzleDBIDFromUUID :one
SELECT id FROM puzzles WHERE uuid = $1
`

func (q *Queries) GetPuzzleDBIDFromUUID(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRow(ctx, getPuzzleDBIDFromUUID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateGenerationLogStatus = `-- name: UpdateGenerationLogStatus :execrows
UPDATE puzzle_generation_logs SET completed_at = NOW(), error_status = $1, fulfilled = $2 WHERE id = $3
`

type UpdateGenerationLogStatusParams struct {
	ErrorStatus pgtype.Text
	Fulfilled   pgtype.Bool
	ID          int64
}

func (q *Queries) UpdateGenerationLogStatus(ctx context.Context, arg UpdateGenerationLogStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGenerationLogStatus, arg.ErrorStatus, arg.Fulfilled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPuzzleVote = `-- name: UpsertPuzzleVote :execrows
INSERT INTO puzzle_votes (puzzle_id, user_id, vote) VALUES ($1, $2, $3)
ON CONFLICT (puzzle_id, user_id) DO UPDATE SET vote = $3
`

type UpsertPuzzleVoteParams struct {
	PuzzleID int64
	UserID   int64
	Vote     pgtype.Int4
}

func (q *Queries) UpsertPuzzleVote(ctx context.Context, arg UpsertPuzzleVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPuzzleVote, arg.PuzzleID, arg.UserID, arg.Vote)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
