// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addListItem = `-- name: AddListItem :exec
INSERT INTO liststats (game_id, player_id, timestamp, stat_type, item)
VALUES ($1, $2, $3, $4, $5)
`

type AddListItemParams struct {
	GameID    pgtype.Text
	PlayerID  pgtype.Text
	Timestamp pgtype.Int8
	StatType  pgtype.Int4
	Item      []byte
}

func (q *Queries) AddListItem(ctx context.Context, arg AddListItemParams) error {
	_, err := q.db.Exec(ctx, addListItem,
		arg.GameID,
		arg.PlayerID,
		arg.Timestamp,
		arg.StatType,
		arg.Item,
	)
	return err
}

const getListItems = `-- name: GetListItems :many
SELECT game_id, player_id, timestamp, item FROM liststats
WHERE stat_type = $1
  AND ($2::text = '' OR player_id = $2)
  AND game_id = ANY($3::text[])
ORDER BY timestamp
`

type GetListItemsParams struct {
	StatType pgtype.Int4
	PlayerID string
	GameIds  []string
}

type GetListItemsRow struct {
	GameID    pgtype.Text
	PlayerID  pgtype.Text
	Timestamp pgtype.Int8
	Item      []byte
}

func (q *Queries) GetListItems(ctx context.Context, arg GetListItemsParams) ([]GetListItemsRow, error) {
	rows, err := q.db.Query(ctx, getListItems, arg.StatType, arg.PlayerID, arg.GameIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListItemsRow
	for rows.Next() {
		var i GetListItemsRow
		if err := rows.Scan(
			&i.GameID,
			&i.PlayerID,
			&i.Timestamp,
			&i.Item,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
