// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournament_directors.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTournamentDirector = `-- name: AddTournamentDirector :exec
INSERT INTO tournament_directors (tournament_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (tournament_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddTournamentDirectorParams struct {
	TournamentID int32
	UserID       int32
	Role         TournamentDirectorRole
}

func (q *Queries) AddTournamentDirector(ctx context.Context, arg AddTournamentDirectorParams) error {
	_, err := q.db.Exec(ctx, addTournamentDirector, arg.TournamentID, arg.UserID, arg.Role)
	return err
}

const getTournamentDirectorByUUID = `-- name: GetTournamentDirectorByUUID :one
SELECT td.role
FROM tournaments t
JOIN tournament_directors td ON td.tournament_id = t.id AND td.user_id = $2
WHERE t.uuid = $1
`

type GetTournamentDirectorByUUIDParams struct {
	Uuid   pgtype.Text
	UserID int32
}

// Returns the director's role for the given tournament UUID and user ID.
// Returns pgx.ErrNoRows if the user is not a director of this tournament.
func (q *Queries) GetTournamentDirectorByUUID(ctx context.Context, arg GetTournamentDirectorByUUIDParams) (TournamentDirectorRole, error) {
	row := q.db.QueryRow(ctx, getTournamentDirectorByUUID, arg.Uuid, arg.UserID)
	var role TournamentDirectorRole
	err := row.Scan(&role)
	return role, err
}

const getTournamentNumericID = `-- name: GetTournamentNumericID :one
SELECT id FROM tournaments WHERE uuid = $1
`

func (q *Queries) GetTournamentNumericID(ctx context.Context, uuid pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, getTournamentNumericID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listTournamentDirectors = `-- name: ListTournamentDirectors :many
SELECT u.id AS user_id, u.uuid AS user_uuid, u.username, td.role
FROM tournament_directors td
JOIN users u ON td.user_id = u.id
WHERE td.tournament_id = $1
ORDER BY td.created_at ASC
`

type ListTournamentDirectorsRow struct {
	UserID   int32
	UserUuid pgtype.Text
	Username pgtype.Text
	Role     TournamentDirectorRole
}

func (q *Queries) ListTournamentDirectors(ctx context.Context, tournamentID int32) ([]ListTournamentDirectorsRow, error) {
	rows, err := q.db.Query(ctx, listTournamentDirectors, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTournamentDirectorsRow
	for rows.Next() {
		var i ListTournamentDirectorsRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserUuid,
			&i.Username,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentsByDirector = `-- name: ListTournamentsByDirector :many
SELECT t.uuid, t.name, t.slug, t.description, t.type, t.directors, t.extra_meta,
       t.is_started, t.is_finished, t.scheduled_start_time, t.scheduled_end_time,
       t.created_at, t.parent
FROM tournaments t
JOIN tournament_directors td ON td.tournament_id = t.id
WHERE td.user_id = $1
ORDER BY t.created_at DESC
LIMIT $2
`

type ListTournamentsByDirectorParams struct {
	UserID int32
	Limit  int32
}

type ListTournamentsByDirectorRow struct {
	Uuid               pgtype.Text
	Name               pgtype.Text
	Slug               pgtype.Text
	Description        pgtype.Text
	Type               pgtype.Text
	Directors          []byte
	ExtraMeta          []byte
	IsStarted          pgtype.Bool
	IsFinished         pgtype.Bool
	ScheduledStartTime pgtype.Timestamptz
	ScheduledEndTime   pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	Parent             pgtype.Text
}

func (q *Queries) ListTournamentsByDirector(ctx context.Context, arg ListTournamentsByDirectorParams) ([]ListTournamentsByDirectorRow, error) {
	rows, err := q.db.Query(ctx, listTournamentsByDirector, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTournamentsByDirectorRow
	for rows.Next() {
		var i ListTournamentsByDirectorRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Directors,
			&i.ExtraMeta,
			&i.IsStarted,
			&i.IsFinished,
			&i.ScheduledStartTime,
			&i.ScheduledEndTime,
			&i.CreatedAt,
			&i.Parent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTournamentDirector = `-- name: RemoveTournamentDirector :exec
DELETE FROM tournament_directors
WHERE tournament_id = $1 AND user_id = $2
`

type RemoveTournamentDirectorParams struct {
	TournamentID int32
	UserID       int32
}

func (q *Queries) RemoveTournamentDirector(ctx context.Context, arg RemoveTournamentDirectorParams) error {
	_, err := q.db.Exec(ctx, removeTournamentDirector, arg.TournamentID, arg.UserID)
	return err
}

const updateTournamentDirectorRole = `-- name: UpdateTournamentDirectorRole :exec
UPDATE tournament_directors
SET role = $3
WHERE tournament_id = $1 AND user_id = $2
`

type UpdateTournamentDirectorRoleParams struct {
	TournamentID int32
	UserID       int32
	Role         TournamentDirectorRole
}

func (q *Queries) UpdateTournamentDirectorRole(ctx context.Context, arg UpdateTournamentDirectorRoleParams) error {
	_, err := q.db.Exec(ctx, updateTournamentDirectorRole, arg.TournamentID, arg.UserID, arg.Role)
	return err
}
